services:
  - name: poker-planning-web
    type: web
    runtime: node
    plan: free
    envVars:
      - key: NODE_VERSION
        value: 18
    buildCommand: npm install
    startCommand: npm start
    repo: https://github.com/amitesh786/Poker-Planning
    branch: main
